### ISSUE TITLE
Use proxy may cause more stale shares!

### ISSUE THREAD

**Issue by khaman1** [JuicyPasta/Claymore-No-Fee-Proxy#14]
The latest claymore code showed the red message "Miner detected that you use local pool or local stratum proxy. This mode is not currently supported and will cause more stale". Does that affect to the total of the shares I receive? 
P/s: my "rekt" is receiving some shares from faking the devfee address.

Thanks.

**Comment by drdada** [comment]
Hello,
Please read the FAQ and https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/8 and also https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/6
