### ISSUE TITLE
Another coins

### ISSUE THREAD

**Issue by dinho-afsn** [JuicyPasta/Claymore-No-Fee-Proxy#21]
Hello congratulations,
I'm trying to use with claymore 9.4 gpu.
However the format is different from the wallet.

I'm tending like this:
Windows 10 terminal as admin and Bytecoin coins
my pool http://bcn.bbmv.online/en.html#

Stratum_proxy.py 127.0.0.1 8008 bcn.bbmv.online 7777 MYWALLLET

The daemon runs ok.

But the address of the fees appears in the host pool

I'm starting claymores like this:
NsGpuCNMiner94 -o stratum + tcp: //127.0.0.1: 8008 -u MYWALLLET -p x

My wallet has this format here

24yWY3MTJiQQUcMwkRGTrTVteWwGbyhNrigvupkncSYaAXggM5z5Xhm43TLwfNxiN7MzWpYfdewWFAed5GMMmdEmHK5UT4o

He comes to appear on the console that

{"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"809534694370813","job":{"blob":"010094bebdcc05ebe3ec89b90d1688c3a173ba654aa47c368e217e919ada7979e0a7586ec2e224000000007011892f2495bcb1ea53a78afedc4a40893479ab8a4081ef139dae904a36e82201","job_id":"954558903560973","target":"b88d0600"},"status":"OK"}}

[-] budder - {"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"809534694370813","job":{"blob":"010094bebdcc05ebe3ec89b90d1688c3a173ba654aa47c368e217e919ada7979e0a7586ec2e224000000007011892f2495bcb1ea53a78afedc4a40893479ab8a4081ef139dae904a36e82201","job_id":"954558903560973","target":"b88d0600"},"status":"OK"}}

So I guess it's just some adjustment.
If you can help me, I'm very grateful.
Thank you for your help

**Comment by drdada** [comment]
Hello, this proxy is designed for ETH mining with claymore ETH version (which use other alg than yours).
I do not assume any support for other alg, coins or other claymore version.
Feel free to fork the code, analyze, investigate and share your work 👍

**Comment by dinho-afsn** [comment]
Sorry for the inconvenience and thank you.
