### ISSUE TITLE
Can you consider supporting ClaymoreZcash？

### ISSUE THREAD

**Issue by mapleshadow** [JuicyPasta/Claymore-No-Fee-Proxy#22]
Hope to support ClaymoreZcash。Thank you

**Comment by LostSoulFly** [comment]
In the spirit of sharing (and FOSS), my proxy supports Zcash such as Hush and Komodo: https://github.com/LostSoulFly/MinerProxy

**Comment by drdada** [comment]
Hello, this proxy is designed for ETH mining with claymore ETH version (which use other alg than yours).
I do not assume any support for other alg, coins or other claymore version.
Feel free to fork the code, analyze, investigate and share your work 👍
