### ISSUE TITLE
change README

### ISSUE THREAD

**Issue by hayou** [JuicyPasta/Claymore-No-Fee-Proxy#25]
Work with claymore 10.

Thanks for your work.

**Comment by drdada** [comment]
I didn't test it yet.
Can you see any hashrate drop / errors / strange behaviour / Watt increases ?

**Comment by Depozitosuz** [comment]
Any news for 10.0 or 10.2?

**Comment by drdada** [comment]
Please see https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/34#issuecomment-369879469
