### ISSUE TITLE
Dual mining setup question

### ISSUE THREAD

**Issue by memopo** [JuicyPasta/Claymore-No-Fee-Proxy#27]
Hi,

for dual mining should we setup 2 stratum proxy one for ETH and one for the other coin?
in both case should we use the same eth_address we own : 
./proxy.py [localhost1] [localport1] [ethhost1] [ethport1] [same_eth_address]
./proxy.py [localhost2] [localport2] [otherhost2] [otherport2] [same_eth_address]

Thanks.

**Comment by drdada** [comment]
Explained in the Readme: https://github.com/JuicyPasta/Claymore-No-Fee-Proxy#is-it-compatible-with-dual-mode-mining
