### ISSUE TITLE
Job timeout, disconnect

### ISSUE THREAD

**Issue by QuentinHK0** [JuicyPasta/Claymore-No-Fee-Proxy#30]
Hello, 
I try to set up your proxy (Ver 1.4.0) with Claymore (Claymore.CryptoNote.GPU.Miner.v9.7.Beta.-.POOL). 

This is my host file : 
`194.1.1.10   xmr.cryptofake.fr`

My proxy conf file :
`{
    "local_host": "xmr.cryptofake.fr:8888",
    "pool_address": "xmr.crypto-pool.fr:8443",
    "wallet": "<MywalletAdress>",
    "worker": "",
    "ssl": true
}`

My start.bat for Claymore :
`setx GPU_MAX_ALLOC_PERCENT 100
NsGpuCNMiner.exe -o stratum+tcp://xmr.cryptofake.fr:8888 -u <MywalletAdress> X -p x `

Claymore return this : 
https://i.imgur.com/duSv6gh.jpg

I certainly made a mistake but I do not see where. 
Thank's for helping.

**Comment by drdada** [comment]
Hello,
Please RTFM - This proxy is designed for ETH mining with claymore ETH version (which use other alg than yours).
I do not assume any support for other alg, coins or other claymore version.
Feel free to fork the code, analyze, investigate and share your work 👍

**Comment by QuentinHK0** [comment]
Hi,
Thank's for your answer Drdada ! 
I thought of asking the question in the right place but I was wrong. I am using another proxy developed from yours, that of NanMetal. I will ask my question in the right place. Thank you for your work and good luck.
Regards
