### ISSUE TITLE
How to create the fake WAN network in linux?

### ISSUE THREAD

**Issue by kaosstar** [JuicyPasta/Claymore-No-Fee-Proxy#39]
Hello,

I'm primarily using linux for mining, but I'm  a linux noob, and am not quite sure how to set this up. I've already got it running successfully on Windows. Thanks

**Comment by drdada** [comment]
Here are one example picked via google search
https://www.ostechnix.com/how-to-assign-multiple-ip-addresses-to-single-network-card-in-linux/
