### ISSUE TITLE
 Authorization failed

### ISSUE THREAD

**Issue by HavaneFr** [JuicyPasta/Claymore-No-Fee-Proxy#4]
Hello. I've got this : 

DevFee: ETH: Stratum - connecting to 'eu1.ethermine.org' <127.0.0.1> port 4444
DevFee: ETH: Stratum - Connected (eu1.ethermine.org:4444)
ETH: Authorization failed
: {"id":2,"result":false,"error":null}
Stratum - reading socket failed 10038, disconnect
DevFee: ETH: Job timeout, disconnect, retry in 20 sec...

**Comment by drdada** [comment]
Hello,
Which pool did you set ?
Did you set a password for auth to the pool ?

**Comment by HavaneFr** [comment]
Hi

I use alpereum pool, no password

**Comment by drdada** [comment]
I understood what the problem is.
With alpereum, the worker name is separated with a dot "." not a slash "/".

Spot the line
`json_data['params'][0] = worker_name + '/rekt'`
and replace the **/** with a **.**
Like this:
`json_data['params'][0] = worker_name + '.rekt'`

**Comment by HavaneFr** [comment]
It works with a '.' 
Can you enhance the script with the ability to have a worker name after the adress ?

**Comment by drdada** [comment]
Good.
Yes, I will add this in futur releases.

**Comment by drdada** [comment]
I updated the script to handle the workername
https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/commit/81567de5a5bbade8b689effcf8b177c7717bf339
