### ISSUE TITLE
Multiple addresses

### ISSUE THREAD

**Issue by uvxcoin** [JuicyPasta/Claymore-No-Fee-Proxy#5]
Claymore uses random different addresses. 
How do I set this up for that?

So far I have seen 3

us1.ethpool.org:3333
eth-eu.dwarfpool.com:8008
us1.ethermine.org:4444

Launch multiple proxies?? That could get messy

**Comment by drdada** [comment]
Hello,
Which pool did you set ?
The devfee is mined with some pre-configured pool : nanopool, ethpool, dwarfpool and ethermine. The devfee is trying to mine on the same pool as you. So if you choosed a different pool from the list above, it choose randomely. The solution is to redirect (with host file) all the pre-configured pool except the one you use. You will also have to redirect the right port. You can do the trick with both Linux & Win.
I will update the readme file on that point.

**Comment by HavaneFr** [comment]
Hi

I use alpereum pool, no password

**Comment by HavaneFr** [comment]
How can I redirect the 4 ports ofall the  pre-configured pool ?
In the command line, I have only one port redirected

**Comment by drdada** [comment]
As i said, i will update the readme file.

**Comment by drdada** [comment]
I updated it.
You can find the tutorial here: https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/wiki/Redirecting-all-domains-(Win)
Linux link is coming.
Run only one instance of the proxy! Port redirection and host file is enough.

**Comment by HavaneFr** [comment]
Thanks. After the port redirection, I have that :


python stratum_proxy.py 127.0.0.1 4444 eu.alpereum.ch 3002 False
Daemon is launched, do not close this windows
*[!!] Failed to listen on 127.0.0.1:4444 <http://127.0.0.1:4444>*
*[!!] Check for other listening sockets or correct permissions*

**Comment by drdada** [comment]
@HavaneFr 
Make sure the port 4444 is not in use on your system.
Can you provide the claymore arguments you set ?
Did you copy paste the command line for port redirection ?

**Comment by HavaneFr** [comment]
I copy paste the command line for port redirection.
Now  I have for 4444 port :

C:\WINDOWS\system32>netstat -a -n -o | find "4444"
  TCP    127.0.0.1:4444         0.0.0.0:0              LISTENING       4536
  TCP    192.168.1.27:51598     94.23.28.180:4444      TIME_WAIT       0

The first line is always there, the second one when I run claymore miner

**Comment by drdada** [comment]
It seems claymore is connecting to the real pool.
Verify your host file and check if you have this entry: eu1.ethermine.org

**Comment by HavaneFr** [comment]
I don't have this message after removing port redirection:

netsh interface portproxy delete v4tov4 listenport=4444 listenaddress=127.0.0.1

**Comment by HavaneFr** [comment]
I didn't have eu1.ethermine.org

**Comment by HavaneFr** [comment]
It's ok with dwarfwpool in fake pool

**Comment by HavaneFr** [comment]
but same problem :

DevFee: ETH: Stratum - connecting to 'eth-eu.dwarfpool.com' <127.0.0.1>
port 8008
DevFee: ETH: Stratum - Connected (eth-eu.dwarfpool.com:8008)
ETH: Authorization failed
: {"id":2,"result":false,"error":null}
Stratum - reading socket failed 10038, disconnect
DevFee: ETH: Job timeout, disconnect, retry in 20 sec...

**Comment by drdada** [comment]
@HavaneFr I answered you on #4 (https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/4 )
Please next time, reply on the right topic to avoid off topic or duplicate. Thanks

@uvxcoin To avoid spam on this thread, i will close it. I hope that answered your questions.
