### ISSUE TITLE
Local proxy warning

### ISSUE THREAD

**Issue by dhaern** [JuicyPasta/Claymore-No-Fee-Proxy#6]
Hello, I'm new to this program but I dont know if it's working with new Claymore 9.7

I had this "error" when mining

![miner error](https://user-images.githubusercontent.com/7317522/27991904-51441486-647d-11e7-9eef-1a32e65a8995.png)

Miner detected that you use local pool or local stratum proxy.
This mode is not currently supported and will cause more stale shares.

My fake pool is dwarfpool with correct config in host file, stratum_proxy.py and Python 2.7.13 installed. My real pool is nanopool.

It's a problem? Thanks.

**Comment by drdada** [comment]
Hello, 
Don't worry it's just a warning, because the software detect the server with localhost address. Just ignore it
Read the FAQ for more infos.

If you want to remove the warning you can create a fake wan network.

Regards.

**Comment by dhaern** [comment]
Oh ok, thanks! then is it 100% working with 9.7? :)

**Comment by drdada** [comment]
I have not tried it yet.

**Comment by prizrakpk** [comment]
9.7 all set up. But when the dev fee to appear as in the screenshot above, there are rejections, strongly decreases the number of found shares. Please check

**Comment by suspended** [comment]
10% stales with the 9.7 Claymore. Something is up but can't quite put a finger to it

**Comment by dhaern** [comment]
Hello again, could yo add in FAQ section how to create a fake Wan Network for Linux/Windows please??

**Comment by drdada** [comment]
We figured it out. https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/7#issuecomment-315032273
You should try the fake wan trick.

**Comment by zeryx** [comment]
How would one go about implementing the fake wan trick in a Linux/Debian environment?

**Comment by eLvErDe** [comment]
ip addr add 12.34.56.78/32 dev lo
