### ISSUE TITLE
"Impossible to connect to the pool" error.

### ISSUE THREAD

**Issue by MichaelA2014** [JuicyPasta/Claymore-No-Fee-Proxy#8]
Hello guys. I am trying this no fee proxy. I am having a hard time getting it to work. 

I installed python. I edited the python settings and included my wallet there.

I added the "127.0.0.1 eth-us-west1.nanopool.org" to the hosts file

I edited the claymore start command to connect to the fake address "EthDcrMiner64.exe -epool eth-us-west1.nanopool.org:8008 -ewal 0x05a54a................"

I started daemon.
I then started claymore and when it tries to connect to the nano pool it tells me it is unable to connect and it restarting.

I am running a Windows 10 x64. Python 2.7

Please see attached screenshots of the claymore and proxy.

What to do?

Thank you.
![2017-07-10_8-52-01](https://user-images.githubusercontent.com/15806130/28021517-bd5592c8-654d-11e7-80df-d9417c66b13b.jpg)
![2017-07-10_8-51-34](https://user-images.githubusercontent.com/15806130/28021516-bd54be66-654d-11e7-9af9-16e87a761845.jpg)

**Comment by drdada** [comment]
Hello,
In claymore set the pool as `eth-eu.dwarfpool.com:8008` 
In your host file, delete the nano pool entry and add `127.0.0.1 eth-eu.dwarfpool.com`
Keep the rest unchanged.

**Comment by MichaelA2014** [comment]
Drdada thank you for answer!

I am mining on nano pool. What should I do for it? 

Should I use nano pool address instead of dwarf pool?

**Comment by drdada** [comment]
Hello,
Don't worry it's just a warning, because the software detect the server with localhost address. Just ignore it
Read the FAQ for more infos.

If you want to remove the warning you can create a fake wan network.

This is tested with Claymore 9.6.

Regards.

**Comment by dhaern** [comment]
Hello again, could yo add in FAQ section how to create a fake Wan Network for Linux/Windows please??

**Comment by drdada** [comment]
Please see here https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/wiki/Creating-a-fake-WAN-network-(Win)
I will close this issue, if you want to discuss about stale share go here: https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/issues/7
Thanks
