### ISSUE TITLE
Received incomming connections

### ISSUE THREAD

**Issue by VerminSP** [JuicyPasta/Claymore-No-Fee-Proxy#9]
What's wrong? How to fix?

> [+] Received incomming connections from 127.0.0.1:51257[+] Auth in progress with address: MyWallet/rekt
> 
> [+] Received incomming connections from 127.0.0.1:51258
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51259
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51260
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51261
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51262
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51263
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51264
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51265[+] Auth in progress with address: MyWallet/rekt
> 
> [+] Received incomming connections from 127.0.0.1:51266
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51267
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51268[+] Auth in progress with address: MyWallet/rekt
> 
> [+] Received incomming connections from 127.0.0.1:51269
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51270
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51271[+] Auth in progress with address: MyWallet/rekt
> 
> [+] Received incomming connections from 127.0.0.1:51272
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51273
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51274
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51275[+] Auth in progress with address: MyWallet/rekt
> 
> [+] Received incomming connections from 127.0.0.1:51276
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51277
>  [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51278
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51279
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51280
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51281
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51282
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51283
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51284
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51285
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51286
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51287
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51288
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51289
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51290
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51291
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51292
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51293
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51294
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51295
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51296
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51297
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51298
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51299
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51300
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51301
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51302
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51303
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51304
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51305
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51306
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51307
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51308
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51309
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51310
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51311
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51312
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51313
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51314
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51315
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51316
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51317
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51318
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51319
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51320
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51321
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51322
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51323
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51324
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51325
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51326
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51327
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51328
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51329
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51330
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51331
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51332
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51333
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51334
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51335
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51336
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51337
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51338
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51339
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51340
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51341
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51342
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51343
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51344
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51345
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51346
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51347
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51348
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51349
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51350
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51351
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51352
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51353
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51354
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51355
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51356
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51357
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51358
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51359
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51360
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51361
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51362
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51363
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51364
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51365
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51366
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51367
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51368
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51369
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51370
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51371
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51372
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51373
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51374
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51375
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51376
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51377
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51378
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51379
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51380
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51381
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51382
> [+] Auth in progress with address: MyWallet/rekt
> [+] Received incomming connections from 127.0.0.1:51383

**Comment by drdada** [comment]
Hello,
Haha, you missed one thing. 
Edit the script and find the worker_name variable replace the content by your wallet address (and not a text)
For exemple: worker_name = '0xB7716d5A768Bc0d5bc5c216cF2d85023a697D04D'

It may change in futur release.

**Comment by VerminSP** [comment]
Mywallet = my real address (of the form 0xB7716d5A768Bc0d5bc5c216cF2d85023a697D04D) I changed it in the log to hide).

**Comment by drdada** [comment]
Aah Ok ;)
And what are the claymore output ?
Can you send me the arguments you set in claymore ? And the argument in No fee proxy please.
I never had this issue, it's strange because claymore seems sending _rekt_ worker name.

**Comment by VerminSP** [comment]
![git](https://user-images.githubusercontent.com/23242725/28063647-7a97ad48-663a-11e7-8509-5cc29067dd80.jpg)
Log NodevFee [log.txt](https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/files/1138496/log.txt)

**Comment by drdada** [comment]
I see you are using Claymore 7.3, i never tested it. 
Can you try with a 9.5 or 9.6 version ?

**Comment by VerminSP** [comment]
9.5, 9.6.
Checked, all the same, does not work.

**Comment by VerminSP** [comment]
I tried another server eth-eu.dwarfpool.com - it works!
With eth-ru.dwarfpool.com and eth-ru2.dwarfpool.com-it does not work.

**Comment by khaman1** [comment]
I have tested the code with Claymore 9.7. Everything is working really well

**Comment by drdada** [comment]
@VerminSP Oh i figured it out. I didn't notice before but, the pool you set in claymore is the same as your real pool.
Set a fake pool in claymore (for exemple `eth-eu.dwarfpool.com:8008`)
Make sure `eth-eu.dwarfpool.com:8008` is in your host file and your real pool (here _eth-eu.dwarfpool.com_) is **NOT** in your host file.
